name: stop_loss_update_env
channels:
  - ranaroussi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astroid=2.6.5
  - autopep8=1.5.7
  - bidict=0.21.2
  - blas=1.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2021.7.5
  - chardet=4.0.0
  - click=8.0.1
  - colorama=0.4.4
  - cryptography=3.4.7
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.10.0
  - intel-openmp=2021.3.0
  - isort=5.9.2
  - jmespath=0.10.0
  - krb5=1.19.1
  - lazy-object-proxy=1.6.0
  - ld_impl_linux-64=2.35.1
  - libedit=3.1.20210216
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libopenblas=0.3.13
  - libpq=12.2
  - libstdcxx-ng=9.3.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - llvm-openmp=12.0.1
  - loguru=0.5.3
  - lxml=4.6.3
  - mccabe=0.6.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multitasking=0.0.9
  - ncurses=6.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1k
  - pip=21.1.3
  - psutil=5.8.0
  - psycopg2=2.8.6
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pylint=2.9.5
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.9.5
  - python_abi=3.9
  - pytz=2021.1
  - readline=8.1
  - requests=2.25.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tbb=2021.3.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - trading-calendars=2.1.1
  - typing=3.10.0.0
  - tzdata=2021a
  - wheel=0.36.2
  - wrapt=1.12.1
  - xlsxwriter=1.4.4
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.5.0
  - zlib=1.2.11
