swagger:
  outputDirectory: ./dist_swagger
  entryFile:
    - ./src/**/*.rest.ts
    - ./src/server.ts
  outputFormat: OpenApi_3
  name: docs server
  description: schema for rest docs
  ignore:
    - /node_modules/**
