name: factor_model_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20200225.2
  - arrow-cpp=4.0.1
  - astroid=2.6.6
  - autopep8=1.5.7
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blpapi=3.16.2
  - boost-cpp=1.73.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cycler=0.10.0
  - dbus=1.13.18
  - double-conversion=3.1.5
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gettext=0.21.0
  - gflags=2.2.2
  - glib=2.68.2
  - glib-tools=2.68.2
  - glog=0.5.0
  - grpc-cpp=1.28.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.3.0
  - isort=5.9.3
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libedit=3.1.20210714
  - libev=4.33
  - libevent=2.1.8
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libthrift=0.13.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mccabe=0.6.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numexpr=2.7.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - orc=1.6.7
  - patsy=0.5.1
  - pcre=8.45
  - pdblp=0.1.8
  - pillow=8.3.1
  - pip=21.2.4
  - psutil=5.8.0
  - pthread-stubs=0.3
  - py4j=0.10.9.2
  - pyarrow=4.0.1
  - pycodestyle=2.7.0
  - pylint=2.9.6
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyspark=3.1.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - qt=5.9.7
  - re2=2020.11.01
  - readline=8.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - seaborn-base=0.11.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tbb=2021.3.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - typed-ast=1.4.3
  - tzdata=2021a
  - uriparser=0.9.3
  - utf8proc=2.6.1
  - wheel=0.37.0
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
