name: ssmif_factor_model_new
channels:
  - ranaroussi
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - autopep8=1.5.4
  - blpapi=3.14.0
  - brotlipy=0.7.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=3.1.1
  - cycler=0.10.0
  - freetype=2.10.2
  - idna=2.10
  - joblib=0.16.0
  - jpeg=9d
  - kiwisolver=1.2.0
  - keras=2.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - loguru=0.5.0
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - multitasking=0.0.9
  - ncurses=6.2
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.1
  - patsy=0.5.1
  - pdblp=0.1.8
  - pillow=7.2.0
  - pip=20.2.2
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.24.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - urllib3=1.25.10
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
