name: stock_data_update_env
channels:
  - ranaroussi
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astroid=2.4.2
  - autopep8=1.5.6
  - bidict=0.21.2
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.3.1
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.2
  - isort=5.7.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.35.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libopenblas=0.3.10
  - libpq=12.2
  - libstdcxx-ng=9.3.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - loguru=0.5.3
  - lxml=4.6.3
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.0.2
  - multitasking=0.0.9
  - ncurses=6.2
  - openssl=1.1.1k
  - pandas-datareader=0.9.0
  - pip=20.3.3
  - psutil=5.8.0
  - psycopg2=2.8.5
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.9.1
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - readline=8.0
  - requests=2.25.1
  - setuptools=49.6.0
  - sqlite=3.34.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - trading-calendars=2.1.1
  - typing=3.7.4.3
  - tzdata=2020f
  - wheel=0.36.2
  - wrapt=1.11.2
  - xlsxwriter=1.3.7
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
